name: Synchro Calendrier iCloud

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Telecharger le fichier ICS
        run: curl -sL "https://p187-caldav.icloud.com/published/2/MTAyMzg3MTMyMTEwMjM4N3g4ajosgZu2q9IYau8yaejsyQdBg9avVSVaQccExs-XrtlUWT9yWIQOAow4PO0D-1SVX0xBo-DA585ETY76Hrg" -o booking.ics

      - name: Commit et Push des changements
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add booking.ics
          git commit -m "Mise a jour auto du calendrier" || exit 0
          git push
